updated countdown timer placement to SubHeading Area
Lid-Protocol/presale-dapp pull request #2
Opened 2020-10-01 00:53 UTC by Klongrich

2020-10-07 07:14 UTC, carlsbad-sunshine commented on src/components/EndTimer.tsx
> -    </Box>
Yes this is required

2020-10-09 18:35 UTC, ethereal-nfts commented on src/components/EndTimer.tsx
> -    </Box>
@Klongrich Still waiting for the hardap timer display to be added back in

2020-10-09 18:37 UTC, carlsbad-sunshine commented on src/components/EndTimer.tsx
> -    </Box>
@Klongrich Still waiting for the hardcap timer to be added back in

2020-10-09 18:39 UTC, Klongrich commented on src/components/EndTimer.tsx
> -    </Box>
should be added

2020-10-09 23:14 UTC, iamonuwa requested changes
@Klongrich please remove the web3modal pop up on initial page load. Allow the user to call it first.

2020-10-12 05:17 UTC, Klongrich commented
> @Klongrich please remove the web3modal pop up on initial page load. Allow the user to call it first.

Okay, Would you want to have that on a different PR? Just makes it more organized. (:

2020-10-12 05:17 UTC, closed without merging

2020-10-12 05:24 UTC, Klongrich commented
> @Klongrich please remove the web3modal pop up on initial page load. Allow the user to call it first.

Miss-clicked and closed PR on accident. Would you want to have that update on a new PR? I have some of the fixes on a different branch.